global:
  scrape_interval: 5s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: worker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["worker:8080"]
