spring:
  application:
    name: tr1l-billing

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate: create-drop

# 복호화 관련 환경변수
secret-key: ${SECRET_KEY}
algorithm: ${ALGORITHM}
transformation: ${TRANSFORMATION}