kafka:
  topic:
    dispatch-events: dispatch-events-v1
    delivery-result-events: delivery-result-events-v1
  group:
    delivery: delivery-group
    delivery-result-handler: delivery-result-handler-group

secret-key: "12345678901234567890123456789012"

spring:
  application:
    name: delivery-server

  profiles:
    default: local

  config:
    import:
      - postgres.yml
      - kafka.yml

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
