spring:
  main:
    web-application-type: none  # 톰캣 기동 방지 (핵심)
    banner-mode: "off"          # 로그 가독성을 위해 선택사항
  application:
    name: dispatch-server

  profiles:
    default: local

  config:
    import:
      - postgres.yml
      - kafka.yml

  cloud:
    aws:
      region:
        static: ap-northeast-2  # 서울 리전 (또는 us-east-1 등 아무거나)
      stack:
        auto: false             # CloudFormation 스택 자동 조회 방지 (필수)
      credentials: # 로컬 테스트용 가짜 키 (없으면 또 에러 날 수 있음)
        access-key: test
        secret-key: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 500
        order_inserts: true
        order_updates: true

server:
  port: 8080

kafka:
  topic:
    dispatch-events: ${KAFKA_TOPIC_DISPATCH_EVENTS:dispatch-events-v1}

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO





